# -*- coding: utf-8 -*-
"""train_network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwBz1CC6QMV5EwS1JNoWQ-rbA-QwxNtp
"""

# =====================================================
# train_network_bitboard.py
#   - ビットボード履歴で Dual Net を再学習
# =====================================================
from pathlib import Path
import numpy as np
import pickle, os, sys
from tensorflow.keras.models import load_model
from tensorflow.keras.callbacks import LearningRateScheduler, LambdaCallback
from tensorflow.keras import backend as K

from dual_network import DN_INPUT_SHAPE         # (4,4,8)

RN_EPOCHS = 20          # エポック数
SIZE      = DN_INPUT_SHAPE[0]                   # 4

# -----------------------------------------------------
# 盤面 64bit → (4,4,8) テンソル  *ベクトル化版*
# -----------------------------------------------------
def bitboards_to_tensor_batch(pieces_arr, enemy_arr):
    """
    pieces_arr, enemy_arr : (N,) uint64 配列
    return                : (N,4,4,8) float32
    """
    N = len(pieces_arr)
    # 64bit → (N,64) bool
    mine_bits  = np.unpackbits(pieces_arr.view(np.uint8)
                               .reshape(N, 8),  # little-endian
                               bitorder='little')
    yours_bits = np.unpackbits(enemy_arr.view(np.uint8)
                               .reshape(N, 8),
                               bitorder='little')

    # reshape → (N,4,4,4)  (z,y,x)
    mine  = mine_bits.reshape(N, SIZE, SIZE, SIZE)
    yours = yours_bits.reshape(N, SIZE, SIZE, SIZE)

    # 軸並べ替え → (N,y,x,z) = (N,4,4,4)
    mine  = mine.transpose(0, 2, 3, 1)          # ch0-3
    yours = yours.transpose(0, 2, 3, 1)         # ch4-7

    planes = np.zeros((N, SIZE, SIZE, SIZE * 2), dtype=np.float32)
    planes[..., :SIZE]  = mine
    planes[..., SIZE:]  = yours
    return planes

# -----------------------------------------------------
# リプレイ読み込み
# -----------------------------------------------------
def load_history():
    hist_files = sorted(Path("./data").glob("*.history"))
    if not hist_files:
        print("❌  data/*.history がありません。self_play を回してください。")
        sys.exit()
    with hist_files[-1].open("rb") as f:
        return pickle.load(f)

# -----------------------------------------------------
# 学習ループ
# -----------------------------------------------------
def train_network():
    history = load_history()

    pieces_int, enemy_int = zip(*[h[0] for h in history])
    y_policies, y_values  = zip(*[(h[1], h[2]) for h in history])

    pieces_arr = np.frombuffer(np.array(pieces_int, dtype=np.uint64), dtype=np.uint64)
    enemy_arr  = np.frombuffer(np.array(enemy_int,  dtype=np.uint64), dtype=np.uint64)

    # --- 入力テンソル (N,4,4,8)
    xs = bitboards_to_tensor_batch(pieces_arr, enemy_arr)

    # ★ デバッグ ── non-zero 要素数を確認 ★
    print("DEBUG  xs[0] non-zero =", xs[0].sum())

    # --- 出力ラベル
    y_policies = np.asarray(y_policies, dtype=np.float32)
    y_values   = np.asarray(y_values,   dtype=np.float32)

    # --- モデル取得
    if not Path("./model/best.h5").exists():
        from dual_network import dual_network
        dual_network()
    model = load_model("./model/best.h5", compile=False)

    model.compile(
        loss      = ["categorical_crossentropy", "mse"],
        optimizer = "adam"
    )

    # --- 学習率スケジューラ
    #def step_decay(epoch):
        #return 0.00025 if epoch >= 80 else 0.0005 if epoch >= 50 else 0.0003 #エポック数を100→20に変更
    def step_decay(epoch):
        return 0.0001 if e>=15 else 0.0002 if e>=8 else 0.0003
    lr_sched = LearningRateScheduler(step_decay, verbose=0)

    # --- 進捗表示
    print_cb = LambdaCallback(
        on_epoch_begin=lambda epoch, logs:
            print(f"\rTrain {epoch+1}/{RN_EPOCHS}", end="")
    )

    # --- 学習
    model.fit(
        xs, [y_policies, y_values],
        batch_size = 128,
        epochs     = RN_EPOCHS,
        verbose    = 0,
        callbacks  = [lr_sched, print_cb]
    )
    print()  # 改行

    # --- 保存
    os.makedirs("./model", exist_ok=True)
    model.save("./model/latest.h5")
    K.clear_session()

# -----------------------------------------------------
# 動作確認
# -----------------------------------------------------
if __name__ == "__main__":
    train_network()

